name: ssh deploy
on:
  push:
    tags:        
      - v*

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dokku
      uses: dokku/github-action@9c1a871eab9daef563cf08b9602c7675f4a8bb56
      with:
        git_remote_url: ssh://dokku@${{ secrets.SSH_SERVER }}:22/wbo
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
